
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;
import java.sql.*;
import java.util.Date;
import java.time.*;
import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mustafa Mokashi
 */
public class markattendance extends javax.swing.JFrame {

    /**
     * Creates new form markattendance
     */
    public markattendance() {
        initComponents();
        facultydisplay();
       
    }

    private void display(String xx)
    {
        try{
                
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/attendance_management","faculty","pass123");
                System.out.println("Connection to the database");
                
                String sql1= "SELECT * FROM attendance where att_date='"+xx+"'";
                PreparedStatement sm=con.prepareStatement(sql1);
                
                
                ResultSet rs=sm.executeQuery(sql1);
                
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
               /* while(rs.next())
                {
                String id=String.valueOf(rs.getInt("d_id"));
                String name1=rs.getString("d_name");
                
                String tabledata[]={id, name1};
                DefaultTableModel tablemodel=(DefaultTableModel)jTable1.getModel();
                
                tablemodel.addRow(tabledata);
                } */
                
                
                    
               con.close();     
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e.getMessage());
        }
    }

    public void facultydisplay(){
        try{
                
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/attendance_management","faculty","pass123");
                System.out.println("Connection to the database");
                
                Statement stm=con.createStatement();
                
                String sql1= "SELECT f_id From faculty";
                ResultSet rs=stm.executeQuery(sql1);

                while(rs.next())
                {
                String id=String.valueOf(rs.getInt("f_id"));
                facultybox.addItem(id);
                }
                con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selectdate = new javax.swing.JLabel();
        datechooser = new com.toedter.calendar.JDateChooser();
        facultybox = new javax.swing.JComboBox<>();
        selectfaculty = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        coursebox = new javax.swing.JComboBox<>();
        timebox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        studentid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pabox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        dfname = new javax.swing.JLabel();
        dcname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Attendance Marking");

        selectdate.setText("Select Date:");

        facultybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyboxActionPerformed(evt);
            }
        });

        selectfaculty.setText("Select faculty ID:");

        jLabel2.setText("Select Course ID:");

        coursebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseboxActionPerformed(evt);
            }
        });

        jLabel3.setText("Time:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        studentid.setToolTipText("Student ID");
        studentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentidActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter Student ID: ");

        jLabel5.setText("Present/Absent:");

        pabox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P", "A" }));
        pabox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paboxActionPerformed(evt);
            }
        });

        jButton1.setText("Save & Lock");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dfname.setText("Faculty Name");

        dcname.setText("Course Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(selectfaculty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(facultybox, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(studentid)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pabox, 0, 118, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(coursebox, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timebox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dfname, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(dcname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dfname)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dcname, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(datechooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(facultybox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(selectfaculty)
                        .addComponent(jLabel2)
                        .addComponent(coursebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(timebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(selectdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(pabox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(87, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void facultyboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyboxActionPerformed
        // TODO add your handling code here:
        
        String sitem=facultybox.getSelectedItem().toString();
        try{
                
              Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/attendance_management","faculty","pass123");
                System.out.println("Connection to the database");
                
                Statement stm=con.createStatement();
                
                String sql2= "SELECT c_id,c_name From course where f_id='"+sitem+"'";
                ResultSet rs=stm.executeQuery(sql2);
                coursebox.removeAllItems();
                while(rs.next())
                {
                String id1=String.valueOf(rs.getInt("c_id"));
                coursebox.addItem(id1);
                String cnaame=rs.getString("c_name");
                dcname.setText(cnaame);
                }

        
        
        String sitem1=coursebox.getSelectedItem().toString();
                        Date date = datechooser.getDate();
                        LocalDateTime ldt = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
                        DayOfWeek dow = ldt.getDayOfWeek();
                        String dayn=dow.name();
                        System.out.println(dayn);
                
                String sql3= "SELECT s_time From time_table where c_id='"+sitem1+"' and day='"+dayn+"'";
                rs=stm.executeQuery(sql3);
                timebox.removeAllItems();
                while(rs.next())
                {
                String id5=String.valueOf(rs.getTime("s_time"));
                timebox.addItem(id5);
                }
                
             String sql44= "SELECT fF_name From faculty where f_id='"+sitem+"'";
                rs=stm.executeQuery(sql44);
                while(rs.next()){
                String fnaame=rs.getString("fF_name");
                dfname.setText(fnaame);
                }
 
                
                
               con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e.getMessage());
        }
        
        
    }//GEN-LAST:event_facultyboxActionPerformed

    private void courseboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseboxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_courseboxActionPerformed


    
    
    private void studentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentidActionPerformed
        // TODO add your handling code here:

            
    }//GEN-LAST:event_studentidActionPerformed

    private void paboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paboxActionPerformed

    String studid=new String();
    String courseid=new String();
    String status=new String();
    String attDate=new String();
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        studid=studentid.getText();
        courseid=coursebox.getSelectedItem().toString();
        status=pabox.getSelectedItem().toString();
        Date dt1;
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        dt1=datechooser.getDate();
        attDate=(String) sdf.format(datechooser.getDate());
        
        display(attDate);
        
        System.out.println(studid);
        System.out.println(courseid);
        System.out.println(status);
        System.out.println(attDate);

        try{
                
              Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/attendance_management","faculty","pass123");
                System.out.println("Connection to the database");
                
                Statement stm=con.createStatement();
                
                
                
                String sqlins= "insert into attendance "+"(att_date, status, s_id, c_id) "+ "values('"+attDate+"', '"+status+"', '"+studid+"', '"+courseid+"');";
                stm.executeUpdate(sqlins);
                
                String sql0="call updatepercent";
                stm.executeQuery(sql0);
                
                display(attDate);

               con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e.getMessage());
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(markattendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(markattendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(markattendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(markattendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new markattendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> coursebox;
    private com.toedter.calendar.JDateChooser datechooser;
    private javax.swing.JLabel dcname;
    private javax.swing.JLabel dfname;
    private javax.swing.JComboBox<String> facultybox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> pabox;
    private javax.swing.JLabel selectdate;
    private javax.swing.JLabel selectfaculty;
    private javax.swing.JTextField studentid;
    private javax.swing.JComboBox<String> timebox;
    // End of variables declaration//GEN-END:variables
}
